# Generated by Django 4.0.3 on 2022-03-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COTObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cot_uid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CPTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=128)),
                ('cot_uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpweb.cotobject')),
            ],
        ),
    ]
