# Generated by Django 4.0.3 on 2022-03-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotobject',
            options={'ordering': ['uid']},
        ),
        migrations.AlterModelOptions(
            name='cptransform',
            options={'ordering': ['cot_uid']},
        ),
        migrations.RemoveField(
            model_name='cotobject',
            name='cot_uid',
        ),
        migrations.AddField(
            model_name='cotobject',
            name='uid',
            field=models.CharField(default='xxx', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
