# Generated by Django 4.0.3 on 2022-03-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpweb', '0002_alter_cotobject_options_alter_cptransform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cptransform',
            name='cot_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='cptransform',
            name='icon',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='cptransform',
            name='callsign',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
