# Generated by Django 4.0.3 on 2022-04-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpweb', '0003_cptransform_cot_type_cptransform_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('defaultGroup', models.CharField(blank=True, max_length=128)),
                ('skipResize', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cotobject',
            options={'ordering': ['uid'], 'verbose_name': 'COT Object', 'verbose_name_plural': 'COT Objects'},
        ),
        migrations.AlterModelOptions(
            name='cptransform',
            options={'ordering': ['cot_uid'], 'verbose_name': 'Transform', 'verbose_name_plural': 'Transforms'},
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type2525b', models.CharField(max_length=128, unique=True)),
                ('iconset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpweb.iconset')),
            ],
        ),
        migrations.AlterField(
            model_name='cptransform',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpweb.icon'),
        ),
    ]
