# Generated by Django 4.0.3 on 2022-06-30 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpweb', '0003_cotobject_n_number_cptransform_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=32)),
                ('url', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'Video Link',
                'verbose_name_plural': 'Video Links',
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='cptransform',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpweb.video'),
        ),
    ]
