# Generated by Django 4.0.3 on 2022-04-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpweb', '0004_iconset_alter_cotobject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cptransform',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iconset',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='icon',
            name='type2525b',
            field=models.CharField(max_length=128),
        ),
    ]
