# Generated by Django 4.0.3 on 2022-04-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpweb', '0005_cptransform_active_iconset_name_alter_icon_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'ordering': ['name', 'type2525b'], 'verbose_name': 'Icon', 'verbose_name_plural': 'Icons'},
        ),
        migrations.AlterModelOptions(
            name='iconset',
            options={'ordering': ['name', 'defaultGroup', 'uid'], 'verbose_name': 'Icon Set', 'verbose_name_plural': 'Icon Sets'},
        ),
    ]
