# Generated by Django 4.0.3 on 2022-04-13 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpweb', '0007_cotobject_created_cptransform_created_icon_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cptransform',
            name='cot_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpweb.cotobject'),
        ),
        migrations.AlterField(
            model_name='cptransform',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpweb.icon'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='iconset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpweb.iconset'),
        ),
    ]
