# Generated by Django 4.0.3 on 2022-04-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpweb', '0008_alter_cptransform_cot_uid_alter_cptransform_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotobject',
            name='id',
        ),
        migrations.AlterField(
            model_name='cotobject',
            name='uid',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cptransform',
            name='callsign',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
