# Generated by Django 4.0.3 on 2022-04-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpweb', '0009_remove_cotobject_id_alter_cotobject_uid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cptransform',
            options={'ordering': ['callsign'], 'verbose_name': 'Transform', 'verbose_name_plural': 'Transforms'},
        ),
    ]
