# Generated by Django 4.0.3 on 2022-05-23 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpweb', '0010_alter_cptransform_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iconset',
            options={'ordering': ['name', 'defaultGroup', 'uuid'], 'verbose_name': 'Icon Set', 'verbose_name_plural': 'Icon Sets'},
        ),
        migrations.RemoveField(
            model_name='iconset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='iconset',
            name='uid',
        ),
        migrations.AddField(
            model_name='cptransform',
            name='agency',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cptransform',
            name='domain',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cptransform',
            name='hex',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cptransform',
            name='model',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cptransform',
            name='reg',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='iconset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cotobject',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cptransform',
            name='callsign',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='cptransform',
            name='cot_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='icon',
            name='type2525b',
            field=models.CharField(max_length=32),
        ),
    ]
